# https://hub.docker.com/r/library/node/tags/
image: node:latest

# AWS access keys stored as secret variables 
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  S3_BUCKET_NAME: $S3_BUCKET_NAME

# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules

stages:
  - build
  - test
  - deploy

# Base build script
.npm_build:
  image: node
  script: 
    - npm install         # Install all dependencies
    - npm run build       # Build the project
  artifacts:
    expire_in: 1 hour
    paths:
      - ./build           # Destination folder to persist

# Base deploy script
.deploy_aws:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - build               # reference from artifact path
  script:
    - aws s3 cp ./build/ s3://$S3_BUCKET_NAME/ --recursive --include "*" 

branch_develop:
  extends: .npm_build
  stage: build
  before_script:
    - export APP_ENV="dev"
  only:
    refs:
      - develop

branch_prod:
  extends: .npm_build
  stage: build
  before_script:
    - export APP_ENV="prod"
  only:
    refs:
      - master

# Test job
test:
  stage: test
  image: node
  script:
    - CI=true npm run test

# Deploy development job
deploy_dev:
  extends: .deploy_aws
  stage: deploy
  dependencies:
    - branch_develop
  before_script:
    - export S3_BUCKET_NAME=$S3_BUCKET_DEV
  only:
    refs:
      - develop

# Deploy production job
deploy_prod:
  extends: .deploy_aws
  stage: deploy
  dependencies:
    - branch_prod
  before_script:
    - export S3_BUCKET_NAME=$S3_BUCKET_PROD
  only:
    refs:
      - master