# https://hub.docker.com/r/library/node/tags/
image: node:latest

#AWS access keys stored as secret variables 
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  S3_BUCKET_NAME: $S3_BUCKET_NAME

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node
  script: 
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - ./build # destination folder
      - node_modules/

test:
  stage: test
  image: node
  script:
    - CI=true npm run test

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - build # reference from artifact path
  script:
    - aws s3 cp ./build/ s3://$S3_BUCKET_NAME/ --recursive --include "*" 